import type { Car, Review } from "@/types";

export const DEMO_CARS: Car[] = [
  {
    id: "1",
    slug: "toyota-camry-2023",
    brand: "Toyota",
    model: "Camry",
    year: 2023,
    price: 18500000,
    mileage: 0,
    body_type: "Седан",
    fuel_type: "Бензин",
    transmission: "Автомат",
    engine_volume: 2.5,
    engine_power: 181,
    drive_type: "Передний",
    color: "Белый перламутр",
    description:
      "Toyota Camry — легендарный бизнес-седан с безупречной репутацией. Просторный салон, богатое оснащение и надёжность, проверенная временем.",
    is_new: true,
    is_active: true,
    is_featured: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    images: [
      {
        id: "1-1",
        car_id: "1",
        url: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=1200&q=85",
        is_main: true,
        sort_order: 0,
      },
      {
        id: "1-2",
        car_id: "1",
        url: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&q=85",
        is_main: false,
        sort_order: 1,
      },
    ],
  },
  {
    id: "2",
    slug: "hyundai-tucson-2023",
    brand: "Hyundai",
    model: "Tucson",
    year: 2023,
    price: 15200000,
    mileage: 0,
    body_type: "Кроссовер",
    fuel_type: "Бензин",
    transmission: "Автомат",
    engine_volume: 2.0,
    engine_power: 150,
    drive_type: "Передний",
    color: "Серебристый металлик",
    description:
      "Hyundai Tucson нового поколения — смелый дизайн, передовые технологии и высокий уровень комфорта. Идеальный городской кроссовер.",
    is_new: true,
    is_active: true,
    is_featured: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    images: [
      {
        id: "2-1",
        car_id: "2",
        url: "https://images.unsplash.com/photo-1633169408895-7f4c5b23bebb?w=1200&q=85",
        is_main: true,
        sort_order: 0,
      },
    ],
  },
  {
    id: "3",
    slug: "kia-sportage-2023",
    brand: "Kia",
    model: "Sportage",
    year: 2023,
    price: 14800000,
    mileage: 0,
    body_type: "Кроссовер",
    fuel_type: "Бензин",
    transmission: "Автомат",
    engine_volume: 2.0,
    engine_power: 150,
    drive_type: "Полный (AWD)",
    color: "Чёрный металлик",
    description:
      "Kia Sportage — динамичный кроссовер с уникальным дизайном и богатым оснащением. Полный привод и просторный салон для активной жизни.",
    is_new: true,
    is_active: true,
    is_featured: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    images: [
      {
        id: "3-1",
        car_id: "3",
        url: "https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=1200&q=85",
        is_main: true,
        sort_order: 0,
      },
    ],
  },
  {
    id: "4",
    slug: "changan-cs55-plus-2023",
    brand: "Changan",
    model: "CS55 Plus",
    year: 2023,
    price: 11500000,
    mileage: 0,
    body_type: "Кроссовер",
    fuel_type: "Бензин",
    transmission: "Автомат",
    engine_volume: 1.5,
    engine_power: 185,
    drive_type: "Передний",
    color: "Синий металлик",
    description:
      "Changan CS55 Plus — стильный кроссовер с турбированным двигателем, богатым оснащением и привлекательной ценой. Отличный выбор для молодых и активных.",
    is_new: true,
    is_active: true,
    is_featured: false,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    images: [
      {
        id: "4-1",
        car_id: "4",
        url: "https://images.unsplash.com/photo-1571987502951-3cc390f9b0e1?w=1200&q=85",
        is_main: true,
        sort_order: 0,
      },
    ],
  },
  {
    id: "5",
    slug: "changan-uni-k-2023",
    brand: "Changan",
    model: "UNI-K",
    year: 2023,
    price: 16800000,
    mileage: 0,
    body_type: "SUV",
    fuel_type: "Бензин",
    transmission: "Автомат",
    engine_volume: 2.0,
    engine_power: 228,
    drive_type: "Полный (AWD)",
    color: "Графитовый",
    description:
      "Changan UNI-K — флагманский кроссовер с премиальным дизайном и мощным двигателем. Просторный семиместный салон и высокие технологии.",
    is_new: true,
    is_active: true,
    is_featured: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    images: [
      {
        id: "5-1",
        car_id: "5",
        url: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&q=85",
        is_main: true,
        sort_order: 0,
      },
    ],
  },
  {
    id: "6",
    slug: "chevrolet-cobalt-2023",
    brand: "Chevrolet",
    model: "Cobalt",
    year: 2023,
    price: 7200000,
    mileage: 0,
    body_type: "Седан",
    fuel_type: "Бензин",
    transmission: "Автомат",
    engine_volume: 1.5,
    engine_power: 106,
    drive_type: "Передний",
    color: "Белый",
    description:
      "Chevrolet Cobalt — надёжный и доступный седан для всей семьи. Просторный салон, экономичный двигатель и отличное соотношение цены и качества.",
    is_new: true,
    is_active: true,
    is_featured: false,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    images: [
      {
        id: "6-1",
        car_id: "6",
        url: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&q=85",
        is_main: true,
        sort_order: 0,
      },
    ],
  },
  {
    id: "7",
    slug: "chevrolet-tracker-2023",
    brand: "Chevrolet",
    model: "Tracker",
    year: 2023,
    price: 11000000,
    mileage: 0,
    body_type: "Кроссовер",
    fuel_type: "Бензин",
    transmission: "Автомат",
    engine_volume: 1.2,
    engine_power: 133,
    drive_type: "Передний",
    color: "Красный металлик",
    description:
      "Chevrolet Tracker — компактный и динамичный кроссовер для города. Турбированный двигатель, стильный дизайн и богатое оснащение.",
    is_new: true,
    is_active: true,
    is_featured: false,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    images: [
      {
        id: "7-1",
        car_id: "7",
        url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&q=85",
        is_main: true,
        sort_order: 0,
      },
    ],
  },
  {
    id: "8",
    slug: "geely-monjaro-2023",
    brand: "Geely",
    model: "Monjaro",
    year: 2023,
    price: 16200000,
    mileage: 0,
    body_type: "SUV",
    fuel_type: "Гибрид",
    transmission: "Автомат",
    engine_volume: 2.0,
    engine_power: 238,
    drive_type: "Полный (4WD)",
    color: "Белый перламутр",
    description:
      "Geely Monjaro — современный гибридный SUV с мощным двигателем. Передовые технологии, просторный семиместный салон и полный привод.",
    is_new: true,
    is_active: true,
    is_featured: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    images: [
      {
        id: "8-1",
        car_id: "8",
        url: "https://images.unsplash.com/photo-1614162692292-7ac56d7f373e?w=1200&q=85",
        is_main: true,
        sort_order: 0,
      },
    ],
  },
  {
    id: "9",
    slug: "byd-song-plus-2023",
    brand: "BYD",
    model: "Song Plus",
    year: 2023,
    price: 14500000,
    mileage: 0,
    body_type: "Кроссовер",
    fuel_type: "Гибрид",
    transmission: "Автомат",
    engine_volume: 1.5,
    engine_power: 204,
    drive_type: "Передний",
    color: "Синий металлик",
    description:
      "BYD Song Plus — инновационный гибридный кроссовер с технологиями будущего. Экономичный, мощный и технологически насыщенный.",
    is_new: true,
    is_active: true,
    is_featured: false,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    images: [
      {
        id: "9-1",
        car_id: "9",
        url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=85",
        is_main: true,
        sort_order: 0,
      },
    ],
  },
  {
    id: "10",
    slug: "lexus-es-2023",
    brand: "Lexus",
    model: "ES",
    year: 2023,
    price: 32000000,
    mileage: 0,
    body_type: "Седан",
    fuel_type: "Гибрид",
    transmission: "Автомат",
    engine_volume: 2.5,
    engine_power: 218,
    drive_type: "Передний",
    color: "Тёмно-синий металлик",
    description:
      "Lexus ES — воплощение японской роскоши и надёжности. Гибридный двигатель, изысканный салон и безупречное качество сборки.",
    is_new: true,
    is_active: true,
    is_featured: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    images: [
      {
        id: "10-1",
        car_id: "10",
        url: "https://images.unsplash.com/photo-1550355291-bbee04a92027?w=1200&q=85",
        is_main: true,
        sort_order: 0,
      },
    ],
  },
  {
    id: "11",
    slug: "mercedes-benz-e-class-2023",
    brand: "Mercedes-Benz",
    model: "E-Class",
    year: 2023,
    price: 45000000,
    mileage: 0,
    body_type: "Седан",
    fuel_type: "Бензин",
    transmission: "Автомат",
    engine_volume: 2.0,
    engine_power: 258,
    drive_type: "Задний",
    color: "Обсидиан чёрный",
    description:
      "Mercedes-Benz E-Class — эталон бизнес-класса. Мощный двигатель, передовые технологии MBUX и непревзойдённый комфорт.",
    is_new: true,
    is_active: true,
    is_featured: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    images: [
      {
        id: "11-1",
        car_id: "11",
        url: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=1200&q=85",
        is_main: true,
        sort_order: 0,
      },
    ],
  },
  {
    id: "12",
    slug: "bmw-5-series-2023",
    brand: "BMW",
    model: "5 Series",
    year: 2023,
    price: 42000000,
    mileage: 0,
    body_type: "Седан",
    fuel_type: "Бензин",
    transmission: "Автомат",
    engine_volume: 2.0,
    engine_power: 245,
    drive_type: "Задний",
    color: "Альпийский белый",
    description:
      "BMW 5 Series — радость вождения и комфорт бизнес-класса в одном автомобиле. Спортивный характер, роскошный салон и инновационные технологии.",
    is_new: true,
    is_active: true,
    is_featured: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    images: [
      {
        id: "12-1",
        car_id: "12",
        url: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&q=85",
        is_main: true,
        sort_order: 0,
      },
    ],
  },
];

export const DEMO_REVIEWS: Review[] = [
  {
    id: "r1",
    name: "Асылбек Нурланов",
    text: "Купил Toyota Camry. Менеджеры помогли с выбором комплектации, оформили кредит за один день. Машина пришла быстро, всё как обещали. Рекомендую!",
    rating: 5,
    car: "Toyota Camry 2023",
    date: "2024-03-15",
  },
  {
    id: "r2",
    name: "Айгуль Сейткалиева",
    text: "Отличный автосалон! Взяла Hyundai Tucson. Очень понравилось отношение персонала — никакого давления, объяснили все нюансы кредита.",
    rating: 5,
    car: "Hyundai Tucson 2023",
    date: "2024-04-02",
  },
  {
    id: "r3",
    name: "Дмитрий Ковалёв",
    text: "Взял Kia Sportage. Цена оказалась лучше, чем у конкурентов. Сервис на высоте, оформление быстрое. Буду рекомендовать друзьям.",
    rating: 5,
    car: "Kia Sportage 2023",
    date: "2024-04-18",
  },
  {
    id: "r4",
    name: "Нурия Исмаилова",
    text: "Очень довольна покупкой BMW 5 Series. Помогли подобрать цвет и комплектацию, организовали тест-драйв. Профессиональная команда!",
    rating: 5,
    car: "BMW 5 Series 2023",
    date: "2024-05-10",
  },
];
