import type { Car, Review } from "@/types";

export const DEMO_CARS: Car[] = [
  {
    id: "1",
    slug: "changan-x5-plus-2023",
    brand: "Changan",
    model: "X5 Plus",
    year: 2023,
    price: 8000000,
    mileage: 0,
    body_type: "SUV",
    fuel_type: "Бензин",
    transmission: "Вариатор",
    engine_volume: 1.5,
    engine_power: 147,
    drive_type: "Передний",
    color: "Чёрный",
    description:
      "Changan X5 Plus — стильный и мощный SUV с турбированным двигателем 1.5T. Спортивный дизайн с красными акцентами, просторный салон с коричневой кожей и панорамный люк.",
    status: "available",
    seats: 5,
    trunk_volume: 440,
    fuel_consumption: 7.5,
    top_speed: 185,
    acceleration: 10.0,
    ground_clearance: 185,
    is_new: true,
    is_active: true,
    is_featured: true,
    created_at: "2025-01-01",
    updated_at: "2025-01-01",
    images: [
      {
        id: "1-1",
        car_id: "1",
        url: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&q=85",
        is_main: true,
        sort_order: 0,
      },
    ],
  },
  {
    id: "2",
    slug: "changan-cs55-plus-2023",
    brand: "Changan",
    model: "CS55 Plus",
    year: 2023,
    price: 9800000,
    mileage: 0,
    body_type: "Кроссовер",
    fuel_type: "Бензин",
    transmission: "Робот",
    engine_volume: 1.5,
    engine_power: 147,
    drive_type: "Передний",
    color: "Белый",
    description:
      "Changan CS55 Plus — современный кроссовер с 7-ступенчатым роботом, широким экраном, коричневым кожаным салоном и богатым оснащением по доступной цене.",
    status: "available",
    seats: 5,
    trunk_volume: 450,
    fuel_consumption: 7.2,
    top_speed: 190,
    acceleration: 9.5,
    ground_clearance: 185,
    is_new: true,
    is_active: true,
    is_featured: true,
    created_at: "2025-01-01",
    updated_at: "2025-01-01",
    images: [
      {
        id: "2-1",
        car_id: "2",
        url: "https://images.unsplash.com/photo-1614162692292-7ac56d7f373e?w=1200&q=85",
        is_main: true,
        sort_order: 0,
      },
    ],
  },
  {
    id: "3",
    slug: "byd-destroyer-05-2023",
    brand: "BYD",
    model: "Destroyer 05",
    year: 2023,
    price: 8100000,
    mileage: 0,
    body_type: "Седан",
    fuel_type: "Гибрид",
    transmission: "Вариатор",
    engine_volume: 1.5,
    engine_power: 204,
    drive_type: "Передний",
    color: "Серый",
    description:
      "BYD Destroyer 05 — инновационный гибридный (DM-i) седан с экономичным расходом 4.4л/100км. Современный интерьер, просторный багажник 450л и мощность системы 204 л.с.",
    status: "available",
    seats: 5,
    trunk_volume: 450,
    fuel_consumption: 4.4,
    top_speed: 170,
    acceleration: 7.3,
    ground_clearance: 170,
    is_new: true,
    is_active: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2025-01-01",
    images: [
      {
        id: "3-1",
        car_id: "3",
        url: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&q=85",
        is_main: true,
        sort_order: 0,
      },
    ],
  },
  {
    id: "4",
    slug: "changan-cs75-pro-2023",
    brand: "Changan",
    model: "CS75 Pro",
    year: 2023,
    price: 10500000,
    mileage: 0,
    body_type: "SUV",
    fuel_type: "Бензин",
    transmission: "Автомат",
    engine_volume: 2.0,
    engine_power: 233,
    drive_type: "Передний",
    color: "Белый",
    description:
      "Changan CS75 Pro — мощный SUV с 2.0-литровым турбодвигателем 233 л.с. и 8-ступенчатым автоматом. Большой объём багажника 535л, роскошный салон с коричневой кожей.",
    status: "available",
    seats: 5,
    trunk_volume: 535,
    fuel_consumption: 8.5,
    top_speed: 215,
    acceleration: 7.9,
    ground_clearance: 185,
    is_new: true,
    is_active: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2025-01-01",
    images: [
      {
        id: "4-1",
        car_id: "4",
        url: "https://images.unsplash.com/photo-1571987502951-3cc390f9b0e1?w=1200&q=85",
        is_main: true,
        sort_order: 0,
      },
    ],
  },
  {
    id: "5",
    slug: "changan-cs75-plus-2023",
    brand: "Changan",
    model: "CS75 Plus",
    year: 2023,
    price: 11000000,
    mileage: 0,
    body_type: "SUV",
    fuel_type: "Бензин",
    transmission: "Автомат",
    engine_volume: 2.0,
    engine_power: 233,
    drive_type: "Передний",
    color: "Серый",
    description:
      "Changan CS75 Plus — топовый SUV с двигателем 2.0T 233 л.с., 8-ступенчатым автоматом и panoramic крышей. Оранжевый кожаный салон, два экрана, клиренс 185 мм.",
    status: "available",
    seats: 5,
    trunk_volume: 535,
    fuel_consumption: 8.5,
    top_speed: 215,
    acceleration: 7.9,
    ground_clearance: 185,
    is_new: true,
    is_active: true,
    is_featured: true,
    created_at: "2025-01-01",
    updated_at: "2025-01-01",
    images: [
      {
        id: "5-1",
        car_id: "5",
        url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&q=85",
        is_main: true,
        sort_order: 0,
      },
    ],
  },
  {
    id: "6",
    slug: "changan-eado-plus-2023",
    brand: "Changan",
    model: "Eado Plus",
    year: 2023,
    price: 7300000,
    mileage: 0,
    body_type: "Седан",
    fuel_type: "Бензин",
    transmission: "Вариатор",
    engine_volume: 1.6,
    engine_power: 123,
    drive_type: "Передний",
    color: "Белый",
    description:
      "Changan Eado Plus — элегантный седан с экономичным 1.6-литровым двигателем, вариатором и просторным салоном. Отличный выбор для ежедневных поездок.",
    status: "available",
    seats: 5,
    trunk_volume: 450,
    fuel_consumption: 6.2,
    top_speed: 175,
    acceleration: 11.5,
    ground_clearance: 160,
    is_new: true,
    is_active: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2025-01-01",
    images: [
      {
        id: "6-1",
        car_id: "6",
        url: "https://images.unsplash.com/photo-1617531653332-bd46c16f4d68?w=1200&q=85",
        is_main: true,
        sort_order: 0,
      },
    ],
  },
  {
    id: "7",
    slug: "changan-eado-2023",
    brand: "Changan",
    model: "Eado",
    year: 2023,
    price: 7600000,
    mileage: 0,
    body_type: "Седан",
    fuel_type: "Бензин",
    transmission: "Робот",
    engine_volume: 1.5,
    engine_power: 156,
    drive_type: "Передний",
    color: "Белый",
    description:
      "Changan Eado — спортивный седан с турбодвигателем 1.5T 156 л.с., 7-ступенчатым роботом и стильным дизайном с красными акцентами. Панорамный люк, большой дисплей.",
    status: "available",
    seats: 5,
    trunk_volume: 450,
    fuel_consumption: 6.8,
    top_speed: 185,
    acceleration: 9.8,
    ground_clearance: 160,
    is_new: true,
    is_active: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2025-01-01",
    images: [
      {
        id: "7-1",
        car_id: "7",
        url: "https://images.unsplash.com/photo-1532581291347-9c39cf10a73c?w=1200&q=85",
        is_main: true,
        sort_order: 0,
      },
    ],
  },
  {
    id: "8",
    slug: "chevrolet-cobalt-2023",
    brand: "Chevrolet",
    model: "Cobalt",
    year: 2023,
    price: 6600000,
    mileage: 0,
    body_type: "Седан",
    fuel_type: "Бензин",
    transmission: "Автомат",
    engine_volume: 1.5,
    engine_power: 106,
    drive_type: "Задний",
    color: "Белый",
    description:
      "Chevrolet Cobalt — надёжный и доступный седан с задним приводом. Вместительный багажник 540л, простой и практичный салон. Идеален для города и трассы.",
    status: "available",
    seats: 5,
    trunk_volume: 540,
    fuel_consumption: 7.5,
    top_speed: 170,
    acceleration: 13.0,
    ground_clearance: 155,
    is_new: true,
    is_active: true,
    is_featured: false,
    created_at: "2025-01-01",
    updated_at: "2025-01-01",
    images: [
      {
        id: "8-1",
        car_id: "8",
        url: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200&q=85",
        is_main: true,
        sort_order: 0,
      },
    ],
  },
  {
    id: "9",
    slug: "deepal-s07-2023",
    brand: "Deepal",
    model: "S07",
    year: 2023,
    price: 11700000,
    mileage: 0,
    body_type: "SUV",
    fuel_type: "Гибрид",
    transmission: "Вариатор",
    engine_volume: 1.5,
    engine_power: 313,
    drive_type: "Передний",
    color: "Белый",
    description:
      "Deepal S07 — флагманский электрический SUV с увеличенным запасом хода. Мощность системы 313 л.с., разгон 0-100 за 5.9с, футуристический дизайн и роскошный оранжевый салон.",
    status: "available",
    seats: 5,
    trunk_volume: 520,
    fuel_consumption: 5.5,
    top_speed: 190,
    acceleration: 5.9,
    ground_clearance: 180,
    is_new: true,
    is_active: true,
    is_featured: true,
    created_at: "2025-01-01",
    updated_at: "2025-01-01",
    images: [
      {
        id: "9-1",
        car_id: "9",
        url: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=1200&q=85",
        is_main: true,
        sort_order: 0,
      },
    ],
  },
];

export const DEMO_REVIEWS: Review[] = [
  {
    id: "r1",
    name: "Jane Akhanova",
    text: "Колжетімді бағa, тез сервис, керемет коммуникация👍 24/7 байланыс, көлікті үйге дейін жеткізіп берді, ризамын! Көп рахмет, істеріңіз берекелі болсын😊",
    rating: 5,
    car: "",
    date: "2026-05-20",
  },
  {
    id: "r2",
    name: "Динара Мукушева",
    text: "Купили машину Easy Motors, приехали, выбрали и уехали! Быстро и оперативно! Во всём помогли, спасибо большое Мейрхану! Побольше Вам продаж и довольных покупателей!",
    rating: 5,
    car: "",
    date: "2026-04-29",
  },
  {
    id: "r3",
    name: "Assel Tasharova",
    text: "Отличный автосалон. Сервис ребят вообще топ, обратная связь и обслуживание даже после продажи) Купила недавно вместе с менеджером Шерханом, забота и коориентированность 24/7, спокойные и развернутые ответы на все вопросы. Спасибо владельцу Меирхану за чуткое отношение и правильных ребят. Процветания вашему делу👍",
    rating: 5,
    car: "",
    date: "2026-04-04",
  },
  {
    id: "r4",
    name: "Нургали Омарханов",
    text: "Осы Авто салонға Рахметімді білдіремін. Осы Авто салоннан көлік алдым, документін барін бір күнде іcтеп, барін түсіндіріп, барін айтып жатыр. Ризамын жігіттерге! Еңбектерің жемісті болсын, іcтерің алга баса берсін. Көлік алсаңызда осы салонға келіп алыңдар, өкінбисіздер. Рахмет.",
    rating: 5,
    car: "",
    date: "2026-03-20",
  },
];
